'use strict';
const { app, BrowserWindow, shell, ipcMain, dialog, session } = require('electron');
const { autoUpdater } = require('electron-updater');
const path = require('path');
const fs = require('fs');
const os = require('os');
const { fork } = require('child_process');

const PORT = process.env.PORT || 3456;
const APP_URL = `http://127.0.0.1:${PORT}`;
const isDev = process.argv.includes('--dev');

const CONFIG_DIR = path.join(os.homedir(), '.mediagrab');
const SESSION_PARTITION = 'persist:mediagrab'; // shared login session for IG/FB

// Must match the User-Agent the server uses for IG/FB API calls, otherwise
// Instagram treats the reused session cookie as suspicious and logs it out.
const APP_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const PLATFORMS = {
  instagram: {
    loginUrl: 'https://www.instagram.com/accounts/login/',
    keyCookie: 'sessionid',
    domains: ['instagram.com', 'cdninstagram.com'],
  },
  facebook: {
    loginUrl: 'https://www.facebook.com/login/',
    keyCookie: 'c_user',
    domains: ['facebook.com', 'fbcdn.net'],
  },
};

let mainWindow = null;
let serverProc = null;

function startServer() {
  return new Promise((resolve, reject) => {
    const serverPath = path.join(__dirname, 'server', 'server.js');
    serverProc = fork(serverPath, [], {
      env: { ...process.env, PORT: String(PORT) },
      stdio: ['ignore', 'pipe', 'pipe', 'ipc'],
    });

    let resolved = false;
    const onData = (buf) => {
      const s = buf.toString();
      process.stdout.write(`[server] ${s}`);
      if (!resolved && /server on http/i.test(s)) {
        resolved = true;
        resolve();
      }
    };
    serverProc.stdout.on('data', onData);
    serverProc.stderr.on('data', (b) => process.stderr.write(`[server] ${b}`));
    serverProc.on('error', reject);
    serverProc.on('exit', (code) => {
      console.log(`[server] exited with code ${code}`);
      if (!resolved) return reject(new Error('Server failed to start'));
      if (app.isQuitting) return;
      // the app is useless without its server — tell the user instead of dying silently
      const msg = code === 90
        ? 'يبدو أن نسخة أخرى من البرنامج شغّالة بالفعل. اقفل النسخ الأخرى ثم أعد فتح البرنامج.'
        : 'توقّف المحرّك الداخلي للبرنامج بشكل غير متوقع. أعد تشغيل البرنامج.';
      dialog.showErrorBox('All In One Media', msg);
      app.quit();
    });

    // safety timeout
    setTimeout(() => { if (!resolved) { resolved = true; resolve(); } }, 8000);
  });
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 860,
    minWidth: 980,
    minHeight: 640,
    backgroundColor: '#0a0c16',
    title: 'All In One Media',
    icon: path.join(__dirname, 'server', 'public', 'assets', 'icon.png'),
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  mainWindow.setMenuBarVisibility(false);
  mainWindow.maximize(); // open filling the whole screen
  mainWindow.loadURL(APP_URL);
  if (isDev) mainWindow.webContents.openDevTools({ mode: 'detach' });

  // open external links in the user's browser (https only — never file:// etc.)
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https:\/\//i.test(url)) shell.openExternal(url);
    return { action: 'deny' };
  });

  mainWindow.on('closed', () => (mainWindow = null));
}

// IPC: reveal a downloaded file in the OS file manager
ipcMain.handle('show-item', (_e, filePath) => {
  if (filePath) shell.showItemInFolder(filePath);
});
ipcMain.handle('open-external', (_e, url) => {
  // config-provided URLs are user-writable — only ever launch https links
  if (url && /^https:\/\//i.test(String(url))) shell.openExternal(url);
});
ipcMain.handle('choose-folder', async () => {
  const r = await dialog.showOpenDialog(mainWindow, { properties: ['openDirectory', 'createDirectory'] });
  if (r.canceled || !r.filePaths.length) return null;
  return r.filePaths[0];
});

// ───────────────────────── in-app login + cookie export ─────────────────────────
function toNetscape(cookies) {
  let out = '# Netscape HTTP Cookie File\n# Generated by MediaGrab\n';
  const fallbackExp = Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 365;
  for (const c of cookies) {
    const includeSub = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiry = Math.floor(c.expirationDate || fallbackExp);
    out += [c.domain, includeSub, c.path || '/', secure, expiry, c.name, c.value].join('\t') + '\n';
  }
  return out;
}

async function exportCookies(platform) {
  const cfg = PLATFORMS[platform];
  const ses = session.fromPartition(SESSION_PARTITION);
  const all = await ses.cookies.get({});
  const filtered = all.filter((c) => cfg.domains.some((d) => c.domain.includes(d)));
  fs.mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });
  const file = path.join(CONFIG_DIR, `cookies-${platform}.txt`);
  fs.writeFileSync(file, toNetscape(filtered), { mode: 0o600 }); // session cookies — owner-only
  const loggedIn = filtered.some((c) => c.name === cfg.keyCookie);
  return { ok: true, count: filtered.length, loggedIn, file };
}

ipcMain.handle('login-platform', async (_e, platform) => {
  const cfg = PLATFORMS[platform];
  if (!cfg) return { ok: false, error: 'unknown platform' };

  const win = new BrowserWindow({
    width: 480,
    height: 760,
    parent: mainWindow,
    modal: false,
    title: `تسجيل الدخول — ${platform}`,
    autoHideMenuBar: true,
    webPreferences: { partition: SESSION_PARTITION, contextIsolation: true, nodeIntegration: false },
  });

  // Use the SAME User-Agent the server will use for API calls (prevents IG from
  // invalidating the session due to a User-Agent mismatch).
  win.webContents.setUserAgent(APP_UA);
  session.fromPartition(SESSION_PARTITION).setUserAgent(APP_UA);

  await win.loadURL(cfg.loginUrl);

  return await new Promise((resolve) => {
    let done = false;
    const finish = async () => {
      if (done) return;
      done = true;
      let result = { ok: false };
      try { result = await exportCookies(platform); } catch (e) { result = { ok: false, error: e.message }; }
      if (!win.isDestroyed()) win.destroy();
      resolve(result);
    };

    const ses = session.fromPartition(SESSION_PARTITION);
    // Consider login complete only once we're past the login / challenge / 2FA /
    // onetap screens AND the session cookie exists — then capture (no premature close).
    const checkLogin = async () => {
      try {
        let url = '';
        try { url = win.webContents.getURL(); } catch {}
        if (/\/accounts\/login|\/challenge|\/two_factor|\/auth_platform|\/accounts\/onetap/.test(url)) return;
        const cookies = await ses.cookies.get({ name: cfg.keyCookie });
        if (cookies && cookies.length) {
          setTimeout(finish, 2500); // let the home feed settle, then capture & close
        }
      } catch {}
    };
    win.webContents.on('did-navigate', checkLogin);
    win.webContents.on('did-frame-navigate', checkLogin);

    // if the user closes the window manually, still export whatever exists
    win.on('closed', () => {
      if (!done) { done = true; exportCookies(platform).then(resolve).catch(() => resolve({ ok: false })); }
    });
  });
});

ipcMain.handle('logout-platform', async (_e, platform) => {
  const cfg = PLATFORMS[platform];
  if (!cfg) return { ok: false };
  try {
    const file = path.join(CONFIG_DIR, `cookies-${platform}.txt`);
    fs.rmSync(file, { force: true });
    const ses = session.fromPartition(SESSION_PARTITION);
    const all = await ses.cookies.get({});
    for (const c of all) {
      if (cfg.domains.some((d) => c.domain.includes(d))) {
        const url = `https://${c.domain.replace(/^\./, '')}${c.path || '/'}`;
        try { await ses.cookies.remove(url, c.name); } catch {}
      }
    }
    return { ok: true };
  } catch (e) { return { ok: false, error: e.message }; }
});

ipcMain.handle('cookies-status', async () => {
  const status = {};
  for (const p of Object.keys(PLATFORMS)) {
    status[p] = fs.existsSync(path.join(CONFIG_DIR, `cookies-${p}.txt`));
  }
  return status;
});

// ───────────────────────── Instagram keyword/hashtag search (logged in) ─────────────────────────

// ───────────────────────── Facebook keyword search (logged-in hidden window) ─────────────────────────
// Facebook locks its search API; we load the real search page in a logged-in
// hidden window (so FB's own JS runs) and scrape the rendered reel/video links.
const FB_EXTRACT = `(() => {
  const out = []; const seen = new Set();
  document.querySelectorAll('a[href*="/reel/"], a[href*="/watch/?v="], a[href*="/videos/"]').forEach(a => {
    const m = a.href.match(/\\/reel\\/(\\d+)|\\/watch\\/\\?v=(\\d+)|\\/videos\\/(\\d+)/);
    if (!m) return;
    const id = m[1] || m[2] || m[3];
    if (!id || seen.has(id)) return; seen.add(id);
    const img = a.querySelector('img');
    out.push({ id, href: a.href.split('?')[0].replace(/#.*$/, ''), thumb: (img && img.src) || '', text: (a.innerText || '').replace(/\\s+/g,' ').trim().slice(0,80) });
  });
  return out;
})()`;

function normalizeArabic(s) {
  return String(s || '')
    .replace(/[ً-ْٰـ]/g, '')
    .replace(/[آأإٱ]/g, 'ا').replace(/ؤ/g, 'و').replace(/ئ/g, 'ي').replace(/ء/g, '').replace(/ى/g, 'ي')
    .replace(/\s+/g, ' ').trim();
}

ipcMain.handle('fb-search', async (_e, query, maxResults) => {
  const max = Math.max(10, Math.min(150, maxResults || 40));
  query = normalizeArabic(query) || query;
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  // OFFSCREEN rendering: the page actually paints (so Facebook's lazy-load fires
  // on scroll) without ever showing a window to the user.
  const win = new BrowserWindow({
    show: false, width: 1200, height: 1600,
    webPreferences: { partition: SESSION_PARTITION, offscreen: true, backgroundThrottling: false, contextIsolation: true, nodeIntegration: false },
  });
  win.webContents.setUserAgent(APP_UA);
  win.webContents.setFrameRate(8);
  win.webContents.on('paint', () => {}); // keep the offscreen compositor active
  try {
    await Promise.race([
      win.loadURL('https://www.facebook.com/search/videos/?q=' + encodeURIComponent(query)),
      sleep(15000),
    ]);
    await sleep(5000);
    let items = [];
    let lastCount = -1, stable = 0;
    for (let i = 0; i < 45; i++) {
      items = await win.webContents.executeJavaScript(FB_EXTRACT).catch(() => items);
      if (items.length >= max) break;
      if (items.length === lastCount) { stable++; if (stable >= 8) break; } else stable = 0;
      lastCount = items.length;
      // real mouse-wheel events drive Facebook's infinite scroll
      for (let k = 0; k < 12; k++) {
        win.webContents.sendInputEvent({ type: 'mouseWheel', x: 600, y: 800, deltaX: 0, deltaY: -700, canScroll: true });
        await sleep(110);
      }
      await win.webContents.executeJavaScript('window.scrollTo(0, document.body.scrollHeight)').catch(() => {});
      await sleep(2300);
    }
    const cards = items.slice(0, max).map((it) => {
      const durMatch = /^(\d+):(\d{2})$/.exec((it.text || '').trim());
      const duration = durMatch ? (parseInt(durMatch[1], 10) * 60 + parseInt(durMatch[2], 10)) : 0;
      const title = (it.text && !durMatch) ? it.text : '(فيديو فيسبوك)';
      return {
        platform: 'facebook',
        id: String(it.id),
        url: it.href.replace(/\/\/[a-z-]+\.facebook\.com/i, '//www.facebook.com'),
        title,
        thumbnail: /^https?:/i.test(it.thumb) ? it.thumb : '',
        duration,
        views: 0,
        author: '',
      };
    });
    return { items: cards };
  } catch (e) {
    return { items: [], error: e.message };
  } finally {
    if (!win.isDestroyed()) win.destroy();
  }
});

// Instagram nests media in several shapes per section; collect from all of them.



// ───────────────────────── auto-update ─────────────────────────
function setupAutoUpdates() {
  if (!app.isPackaged) return; // only in the installed app
  autoUpdater.autoDownload = true;
  autoUpdater.autoInstallOnAppQuit = true;

  autoUpdater.on('update-available', (info) => {
    if (mainWindow) mainWindow.webContents.send('update-status', { state: 'available', version: info.version });
  });
  autoUpdater.on('download-progress', (p) => {
    if (mainWindow) mainWindow.webContents.send('update-status', { state: 'downloading', percent: Math.round(p.percent) });
  });
  autoUpdater.on('update-downloaded', async (info) => {
    if (mainWindow) mainWindow.webContents.send('update-status', { state: 'downloaded', version: info.version });
    const r = await dialog.showMessageBox(mainWindow, {
      type: 'info',
      buttons: ['إعادة التشغيل الآن', 'لاحقاً'],
      defaultId: 0,
      cancelId: 1,
      title: 'تحديث جديد متاح',
      message: `تم تنزيل النسخة ${info.version}.`,
      detail: 'هتتثبّت لما تعيد تشغيل البرنامج.',
    });
    if (r.response === 0) { setImmediate(() => autoUpdater.quitAndInstall()); }
  });
  autoUpdater.on('error', (e) => {
    console.error('[updater] error:', e && e.message);
    // surface it — a silently failing updater looks like "the update never came"
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.executeJavaScript(
        `window.dispatchEvent(new CustomEvent('updater-error'))`
      ).catch(() => {});
    }
  });

  // check on startup, then every 3 hours
  autoUpdater.checkForUpdates().catch(() => {});
  setInterval(() => autoUpdater.checkForUpdates().catch(() => {}), 3 * 60 * 60 * 1000);
}

// hover previews start with sound — allow autoplay without a prior click
app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');

// a second instance would fight over the same port and config — focus the first one
if (!app.requestSingleInstanceLock()) {
  app.quit();
} else {
  app.on('second-instance', () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
  });
}

app.whenReady().then(async () => {
  try {
    await startServer();
  } catch (e) {
    console.error('Failed to start server:', e);
  }
  createWindow();
  setupAutoUpdates();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('before-quit', () => { app.isQuitting = true; });
app.on('quit', () => {
  if (serverProc) try { serverProc.kill(); } catch {}
});
