'use strict';
const { app, BrowserWindow, shell, ipcMain, dialog, session } = require('electron');
const path = require('path');
const fs = require('fs');
const os = require('os');
const { fork } = require('child_process');

const PORT = process.env.PORT || 3456;
const APP_URL = `http://127.0.0.1:${PORT}`;
const isDev = process.argv.includes('--dev');

const CONFIG_DIR = path.join(os.homedir(), '.mediagrab');
const SESSION_PARTITION = 'persist:mediagrab'; // shared login session for IG/FB

// Must match the User-Agent the server uses for IG/FB API calls, otherwise
// Instagram treats the reused session cookie as suspicious and logs it out.
const APP_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const PLATFORMS = {
  instagram: {
    loginUrl: 'https://www.instagram.com/accounts/login/',
    homeHint: /instagram\.com\/?($|\?|#)|instagram\.com\/(?!accounts)/,
    keyCookie: 'sessionid',
    domains: ['instagram.com', 'cdninstagram.com'],
  },
  facebook: {
    loginUrl: 'https://www.facebook.com/login/',
    homeHint: /facebook\.com\/?($|\?|#)/,
    keyCookie: 'c_user',
    domains: ['facebook.com', 'fbcdn.net'],
  },
};

let mainWindow = null;
let serverProc = null;

function startServer() {
  return new Promise((resolve, reject) => {
    const serverPath = path.join(__dirname, 'server', 'server.js');
    serverProc = fork(serverPath, [], {
      env: { ...process.env, PORT: String(PORT) },
      stdio: ['ignore', 'pipe', 'pipe', 'ipc'],
    });

    let resolved = false;
    const onData = (buf) => {
      const s = buf.toString();
      process.stdout.write(`[server] ${s}`);
      if (!resolved && /server on http/i.test(s)) {
        resolved = true;
        resolve();
      }
    };
    serverProc.stdout.on('data', onData);
    serverProc.stderr.on('data', (b) => process.stderr.write(`[server] ${b}`));
    serverProc.on('error', reject);
    serverProc.on('exit', (code) => {
      console.log(`[server] exited with code ${code}`);
      if (!resolved) reject(new Error('Server failed to start'));
    });

    // safety timeout
    setTimeout(() => { if (!resolved) { resolved = true; resolve(); } }, 8000);
  });
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 860,
    minWidth: 980,
    minHeight: 640,
    backgroundColor: '#0a0c16',
    title: 'All In One Media',
    icon: path.join(__dirname, 'server', 'public', 'assets', 'icon.png'),
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  mainWindow.setMenuBarVisibility(false);
  mainWindow.maximize(); // open filling the whole screen
  mainWindow.loadURL(APP_URL);
  if (isDev) mainWindow.webContents.openDevTools({ mode: 'detach' });

  // open external links in the user's browser
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: 'deny' };
  });

  mainWindow.on('closed', () => (mainWindow = null));
}

// IPC: reveal a downloaded file in the OS file manager
ipcMain.handle('show-item', (_e, filePath) => {
  if (filePath) shell.showItemInFolder(filePath);
});
ipcMain.handle('open-external', (_e, url) => {
  if (url) shell.openExternal(url);
});
ipcMain.handle('choose-folder', async () => {
  const r = await dialog.showOpenDialog(mainWindow, { properties: ['openDirectory', 'createDirectory'] });
  if (r.canceled || !r.filePaths.length) return null;
  return r.filePaths[0];
});

// ───────────────────────── in-app login + cookie export ─────────────────────────
function toNetscape(cookies) {
  let out = '# Netscape HTTP Cookie File\n# Generated by MediaGrab\n';
  const fallbackExp = Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 365;
  for (const c of cookies) {
    const includeSub = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiry = Math.floor(c.expirationDate || fallbackExp);
    out += [c.domain, includeSub, c.path || '/', secure, expiry, c.name, c.value].join('\t') + '\n';
  }
  return out;
}

async function exportCookies(platform) {
  const cfg = PLATFORMS[platform];
  const ses = session.fromPartition(SESSION_PARTITION);
  const all = await ses.cookies.get({});
  const filtered = all.filter((c) => cfg.domains.some((d) => c.domain.includes(d)));
  fs.mkdirSync(CONFIG_DIR, { recursive: true });
  const file = path.join(CONFIG_DIR, `cookies-${platform}.txt`);
  fs.writeFileSync(file, toNetscape(filtered));
  const loggedIn = filtered.some((c) => c.name === cfg.keyCookie);
  return { ok: true, count: filtered.length, loggedIn, file };
}

ipcMain.handle('login-platform', async (_e, platform) => {
  const cfg = PLATFORMS[platform];
  if (!cfg) return { ok: false, error: 'unknown platform' };

  const win = new BrowserWindow({
    width: 480,
    height: 760,
    parent: mainWindow,
    modal: false,
    title: `تسجيل الدخول — ${platform}`,
    autoHideMenuBar: true,
    webPreferences: { partition: SESSION_PARTITION, contextIsolation: true, nodeIntegration: false },
  });

  // Use the SAME User-Agent the server will use for API calls (prevents IG from
  // invalidating the session due to a User-Agent mismatch).
  win.webContents.setUserAgent(APP_UA);
  session.fromPartition(SESSION_PARTITION).setUserAgent(APP_UA);

  await win.loadURL(cfg.loginUrl);

  return await new Promise((resolve) => {
    let done = false;
    const finish = async () => {
      if (done) return;
      done = true;
      let result = { ok: false };
      try { result = await exportCookies(platform); } catch (e) { result = { ok: false, error: e.message }; }
      if (!win.isDestroyed()) win.destroy();
      resolve(result);
    };

    const ses = session.fromPartition(SESSION_PARTITION);
    // Consider login complete only once we're past the login / challenge / 2FA /
    // onetap screens AND the session cookie exists — then capture (no premature close).
    const checkLogin = async () => {
      try {
        let url = '';
        try { url = win.webContents.getURL(); } catch {}
        if (/\/accounts\/login|\/challenge|\/two_factor|\/auth_platform|\/accounts\/onetap/.test(url)) return;
        const cookies = await ses.cookies.get({ name: cfg.keyCookie });
        if (cookies && cookies.length) {
          setTimeout(finish, 2500); // let the home feed settle, then capture & close
        }
      } catch {}
    };
    win.webContents.on('did-navigate', checkLogin);
    win.webContents.on('did-frame-navigate', checkLogin);

    // if the user closes the window manually, still export whatever exists
    win.on('closed', () => {
      if (!done) { done = true; exportCookies(platform).then(resolve).catch(() => resolve({ ok: false })); }
    });
  });
});

ipcMain.handle('logout-platform', async (_e, platform) => {
  const cfg = PLATFORMS[platform];
  if (!cfg) return { ok: false };
  try {
    const file = path.join(CONFIG_DIR, `cookies-${platform}.txt`);
    fs.rmSync(file, { force: true });
    const ses = session.fromPartition(SESSION_PARTITION);
    const all = await ses.cookies.get({});
    for (const c of all) {
      if (cfg.domains.some((d) => c.domain.includes(d))) {
        const url = `https://${c.domain.replace(/^\./, '')}${c.path || '/'}`;
        try { await ses.cookies.remove(url, c.name); } catch {}
      }
    }
    return { ok: true };
  } catch (e) { return { ok: false, error: e.message }; }
});

ipcMain.handle('cookies-status', async () => {
  const status = {};
  for (const p of Object.keys(PLATFORMS)) {
    status[p] = fs.existsSync(path.join(CONFIG_DIR, `cookies-${p}.txt`));
  }
  return status;
});

// ───────────────────────── Instagram keyword/hashtag search (logged in) ─────────────────────────
ipcMain.handle('ig-search', async (_e, query) => {
  const tag = String(query || '').replace(/^#/, '').trim();
  if (!tag) return { items: [], error: 'empty' };

  const win = new BrowserWindow({
    show: false,
    webPreferences: { partition: SESSION_PARTITION, contextIsolation: true, nodeIntegration: false },
  });
  try {
    await win.loadURL('https://www.instagram.com/');
    const url = `https://www.instagram.com/api/v1/tags/web_info/?tag_name=${encodeURIComponent(tag)}`;
    const json = await win.webContents.executeJavaScript(
      `fetch(${JSON.stringify(url)}, { headers: { 'x-ig-app-id': '936619743392459' }, credentials: 'include' })
        .then(r => r.json()).catch(() => null)`
    );
    const items = parseIgTagResponse(json);
    return { items };
  } catch (e) {
    return { items: [], error: e.message };
  } finally {
    if (!win.isDestroyed()) win.destroy();
  }
});

// Instagram nests media in several shapes per section; collect from all of them.
function collectMediaFromLayout(lc, sink) {
  if (!lc || typeof lc !== 'object') return;
  if (Array.isArray(lc.medias)) lc.medias.forEach((m) => m && m.media && sink(m.media));
  if (Array.isArray(lc.fill_items)) lc.fill_items.forEach((m) => m && m.media && sink(m.media));
  const obt = lc.one_by_two_item;
  if (obt && obt.clips && Array.isArray(obt.clips.items)) {
    obt.clips.items.forEach((m) => m && m.media && sink(m.media));
  }
}

function igMediaToCard(media) {
  if (!media || !media.code) return null;
  const isVideo = media.media_type === 2 || !!(media.video_versions && media.video_versions.length);
  const isCarousel = media.media_type === 8;
  // keep videos + carousels (often contain video); skip pure images
  if (!isVideo && !isCarousel) return null;
  const cands = media.image_versions2 && media.image_versions2.candidates;
  const thumb = (cands && cands.length && cands[0].url) || '';
  return {
    platform: 'instagram',
    id: String(media.pk || media.id || media.code),
    url: `https://www.instagram.com/${isVideo ? 'reel' : 'p'}/${media.code}/`,
    title: (media.caption && media.caption.text) || '(منشور إنستجرام)',
    thumbnail: thumb,
    duration: media.video_duration || 0,
    views: media.play_count || media.view_count || media.like_count || 0,
    author: (media.user && media.user.username) || '',
  };
}

function parseIgTagResponse(json) {
  if (!json || !json.data) return [];
  const medias = [];
  const buckets = [json.data.top, json.data.recent].filter(Boolean);
  for (const b of buckets) {
    for (const s of (b.sections || [])) collectMediaFromLayout(s.layout_content, (m) => medias.push(m));
  }
  const seen = new Set();
  const out = [];
  for (const m of medias) {
    const card = igMediaToCard(m);
    if (card && !seen.has(card.id)) { seen.add(card.id); out.push(card); }
  }
  return out;
}

app.whenReady().then(async () => {
  try {
    await startServer();
  } catch (e) {
    console.error('Failed to start server:', e);
  }
  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('quit', () => {
  if (serverProc) try { serverProc.kill(); } catch {}
});
